#!/bin/bash
# Example cron script meant to be placed in, e.g.:
# `/etc/cron.hourly/vsphere-janitor` with configuration in
# `/etc/default/vsphere-janitor` as env vars.

set -o errexit

CRON_JOB=$(basename ${BASH_SOURCE[0]})

VSPHERE_JANITOR_USER='nobody'
VSPHERE_JANITOR_LOG_DIR='/var/log'

if [ -f /etc/default/${CRON_JOB} ] ; then
  . /etc/default/${CRON_JOB}
fi

sudo -E -u ${VSPHERE_JANITOR_USER} \
  vsphere-janitor &>> ${VSPHERE_JANITOR_LOG_DIR}/${CRON_JOB}.log
